[2018-06-18 12:00:35] php.DEBUG: Warning: unlink(/var/www/html/symfony/var/cache/de_/ContainerDsqhrjh.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":871,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":665,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 12:54:30] php.DEBUG: Warning: unlink(/var/www/html/symfony/var/cache/de_/ContainerDsqhrjh.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":871,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":665,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 12:54:49] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/web-server-bundle/WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/web-server-bundle/WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 12:55:47] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php\",\"line\":44,\"trace\":[{\"file\":\"/var/www/html/symfony/var/cache/dev/ContainerDsqhrjh/srcDevDebugProjectContainer.php\",\"line\":997,\"function\":\"__construct\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Profiler\\\\FileProfilerStorage\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 12:55:47] php.CRITICAL: Uncaught Exception: Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler). {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:45)"} []
[2018-06-18 12:55:49] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php\",\"line\":44,\"trace\":[{\"file\":\"/var/www/html/symfony/var/cache/dev/ContainerDsqhrjh/srcDevDebugProjectContainer.php\",\"line\":997,\"function\":\"__construct\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Profiler\\\\FileProfilerStorage\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 12:55:49] php.CRITICAL: Uncaught Exception: Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler). {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:45)"} []
[2018-06-18 13:02:58] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php\",\"line\":44,\"trace\":[{\"file\":\"/var/www/html/symfony/var/cache/dev/ContainerDsqhrjh/srcDevDebugProjectContainer.php\",\"line\":997,\"function\":\"__construct\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Profiler\\\\FileProfilerStorage\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:02:58] php.CRITICAL: Uncaught Exception: Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler). {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:45)"} []
[2018-06-18 13:06:59] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php\",\"line\":40,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Adapter/FilesystemAdapter.php\",\"line\":29,\"function\":\"init\",\"class\":\"Symfony\\\\Component\\\\Cache\\\\Adapter\\\\FilesystemAdapter\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:00] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php\",\"line\":140,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/Profiler.php\",\"line\":105,\"function\":\"write\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Profiler\\\\FileProfilerStorage\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:00] php.CRITICAL: Uncaught Exception: Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/77/cb). {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/77/cb). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:141)"} []
[2018-06-18 13:07:00] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/77/cb)." at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php line 141 {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/77/cb). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:141)"} []
[2018-06-18 13:07:00] cache.WARNING: Failed to save key "%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D" (array) {"key":"%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27ae746aaaf1.08977898): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:00] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php\",\"line\":105,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/PhpFilesTrait.php\",\"line\":144,\"function\":\"getFile\",\"class\":\"Symfony\\\\Component\\\\Cache\\\\Adapter\\\\PhpFilesAdapter\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:00] cache.WARNING: Failed to save key "%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D" (integer) {"key":"%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D","type":"integer","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27ae746aaaf1.08977898): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:00] cache.WARNING: Failed to save key "%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D" (array) {"key":"%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27ae746aaaf1.08977898): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:00] cache.WARNING: Failed to save key "%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D" (integer) {"key":"%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D","type":"integer","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27ae746aaaf1.08977898): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:41] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php\",\"line\":40,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Adapter/FilesystemAdapter.php\",\"line\":29,\"function\":\"init\",\"class\":\"Symfony\\\\Component\\\\Cache\\\\Adapter\\\\FilesystemAdapter\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:41] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php\",\"line\":140,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/Profiler.php\",\"line\":105,\"function\":\"write\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Profiler\\\\FileProfilerStorage\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:41] php.CRITICAL: Uncaught Exception: Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/26/67). {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/26/67). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:141)"} []
[2018-06-18 13:07:41] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/26/67)." at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php line 141 {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/26/67). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:141)"} []
[2018-06-18 13:07:41] cache.WARNING: Failed to save key "%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D" (array) {"key":"%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27ae9da50128.21798615): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:41] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php\",\"line\":105,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/PhpFilesTrait.php\",\"line\":144,\"function\":\"getFile\",\"class\":\"Symfony\\\\Component\\\\Cache\\\\Adapter\\\\PhpFilesAdapter\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:41] cache.WARNING: Failed to save key "%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D" (integer) {"key":"%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D","type":"integer","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27ae9da50128.21798615): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:41] cache.WARNING: Failed to save key "%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D" (array) {"key":"%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27ae9da50128.21798615): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:41] cache.WARNING: Failed to save key "%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D" (integer) {"key":"%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D","type":"integer","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27ae9da50128.21798615): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:51] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php\",\"line\":40,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Adapter/FilesystemAdapter.php\",\"line\":29,\"function\":\"init\",\"class\":\"Symfony\\\\Component\\\\Cache\\\\Adapter\\\\FilesystemAdapter\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:51] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php\",\"line\":140,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/Profiler.php\",\"line\":105,\"function\":\"write\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Profiler\\\\FileProfilerStorage\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:51] php.CRITICAL: Uncaught Exception: Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/69/77). {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/69/77). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:141)"} []
[2018-06-18 13:07:51] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/69/77)." at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php line 141 {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/69/77). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:141)"} []
[2018-06-18 13:07:51] cache.WARNING: Failed to save key "%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D" (array) {"key":"%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27aea7a0f741.89518017): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:51] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php\",\"line\":105,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/PhpFilesTrait.php\",\"line\":144,\"function\":\"getFile\",\"class\":\"Symfony\\\\Component\\\\Cache\\\\Adapter\\\\PhpFilesAdapter\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:51] cache.WARNING: Failed to save key "%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D" (integer) {"key":"%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D","type":"integer","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27aea7a0f741.89518017): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:51] cache.WARNING: Failed to save key "%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D" (array) {"key":"%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27aea7a0f741.89518017): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:51] cache.WARNING: Failed to save key "%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D" (integer) {"key":"%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D","type":"integer","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27aea7a0f741.89518017): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:56] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php\",\"line\":40,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Adapter/FilesystemAdapter.php\",\"line\":29,\"function\":\"init\",\"class\":\"Symfony\\\\Component\\\\Cache\\\\Adapter\\\\FilesystemAdapter\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:57] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php\",\"line\":140,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Profiler/Profiler.php\",\"line\":105,\"function\":\"write\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Profiler\\\\FileProfilerStorage\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:57] php.CRITICAL: Uncaught Exception: Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/dc/c4). {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/dc/c4). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:141)"} []
[2018-06-18 13:07:57] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/dc/c4)." at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php line 141 {"exception":"[object] (RuntimeException(code: 0): Unable to create the storage directory (/var/www/html/symfony/var/cache/dev/profiler/dc/c4). at /var/www/html/symfony/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:141)"} []
[2018-06-18 13:07:57] cache.WARNING: Failed to save key "%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D" (array) {"key":"%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27aead22f978.61831452): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:57] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php\",\"line\":105,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/cache/Traits/PhpFilesTrait.php\",\"line\":144,\"function\":\"getFile\",\"class\":\"Symfony\\\\Component\\\\Cache\\\\Adapter\\\\PhpFilesAdapter\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-18 13:07:57] cache.WARNING: Failed to save key "%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D" (integer) {"key":"%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D","type":"integer","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27aead22f978.61831452): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:57] cache.WARNING: Failed to save key "%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D" (array) {"key":"%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D","type":"array","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27aead22f978.61831452): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:07:57] cache.WARNING: Failed to save key "%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D" (integer) {"key":"%5B%5BC%5DSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D","type":"integer","exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/symfony/var/cache/dev/pools/cC+y1aLE8x/5b27aead22f978.61831452): failed to open stream: Permission denied at /var/www/html/symfony/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:87)"} []
[2018-06-18 13:24:58] php.DEBUG: Warning: unlink(/var/www/html/symfony/var/cache/de_/ContainerDsqhrjh.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":871,\"trace\":[{\"file\":\"/var/www/html/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":665,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-19 07:26:49] php.DEBUG: Warning: filemtime(): stat failed for /var/www/html/symfony/config/routes/annotations.yaml {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/PHP-Framework/symfony/vendor/symfony/config/Resource/FileResource.php\",\"line\":63,\"trace\":[{\"file\":\"/var/www/html/PHP-Framework/symfony/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php\",\"line\":34,\"function\":\"isFresh\",\"class\":\"Symfony\\\\Component\\\\Config\\\\Resource\\\\FileResource\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-19 07:48:05] request.INFO: Matched route "home_age". {"route":"home_age","route_parameters":{"_controller":"App\\Controller\\AppController::indexAction","_route":"home_age"},"request_uri":"http://192.168.33.10/PHP-Framework/symfony/public/","method":"GET"} []
[2018-06-19 07:48:05] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 08:43:47] request.INFO: Matched route "home_page". {"route":"home_page","route_parameters":{"_controller":"App\\Controller\\AppController::index","_route":"home_page"},"request_uri":"http://192.168.33.10/PHP-Framework/symfony/public/","method":"GET"} []
[2018-06-19 08:43:47] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 08:43:47] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/" is not callable. Expected method "index" on class "App\Controller\AppController", did you mean "indexAction"?" at /var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 91 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/\" is not callable. Expected method \"index\" on class \"App\\Controller\\AppController\", did you mean \"indexAction\"? at /var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Controller/ControllerResolver.php:91)"} []
[2018-06-19 08:53:10] request.INFO: Matched route "home_age". {"route":"home_age","route_parameters":{"_controller":"App\\Controller\\AppController::indexAction","_route":"home_age"},"request_uri":"http://192.168.33.10/PHP-Framework/symfony/public/","method":"GET"} []
[2018-06-19 08:53:10] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 09:21:53] request.INFO: Matched route "home_age". {"route":"home_age","route_parameters":{"_controller":"App\\Controller\\AppController::indexAction","_route":"home_age"},"request_uri":"http://192.168.33.10/PHP-Framework/symfony/public/","method":"GET"} []
[2018-06-19 09:21:53] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 09:28:45] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)"} []
[2018-06-19 09:28:45] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-06-19 09:29:54] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)"} []
[2018-06-19 09:29:54] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-06-19 09:36:39] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-06-19 09:37:23] console.DEBUG: Command "make:crud" exited with code "1" {"command":"make:crud","code":1} []
[2018-06-19 09:42:49] php.DEBUG: Warning: unlink(/var/www/html/PHP-Framework/symfony/var/cache/de_/ContainerY1rmveu.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":871,\"trace\":[{\"file\":\"/var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":665,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-19 09:43:44] php.DEBUG: Warning: unlink(/var/www/html/PHP-Framework/symfony/var/cache/de_/ContainerY1rmveu.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":871,\"trace\":[{\"file\":\"/var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":665,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-19 10:03:29] request.INFO: Matched route "home_age". {"route":"home_age","route_parameters":{"_controller":"App\\Controller\\AppController::indexAction","_route":"home_age"},"request_uri":"http://192.168.33.10/PHP-Framework/symfony/public/","method":"GET"} []
[2018-06-19 10:03:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 10:05:41] request.INFO: Matched route "home_age". {"route":"home_age","route_parameters":{"_controller":"App\\Controller\\AppController::indexAction","_route":"home_age"},"request_uri":"http://192.168.33.10/PHP-Framework/symfony/public/","method":"GET"} []
[2018-06-19 10:05:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 10:13:15] request.INFO: Matched route "home_age". {"route":"home_age","route_parameters":{"_controller":"App\\Controller\\AppController::indexAction","_route":"home_age"},"request_uri":"http://192.168.33.10/","method":"GET"} []
[2018-06-19 10:13:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 10:23:37] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled." at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php line 168 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:23:37] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:23:37] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:23:37] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled.")." at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:23:37] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:27:45] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled." at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php line 168 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:27:45] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:27:45] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:27:45] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled.")." at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:27:45] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:27:59] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled." at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php line 168 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:27:59] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:27:59] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:27:59] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled.")." at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:27:59] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\Controller\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at /var/www/html/PHP-Framework/symfony/vendor/symfony/twig-bundle/Resources/views/Exception/trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController in /var/www/html/PHP-Framework/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/html/PHP-Framework/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/html/PHP-Framework/symfony/vendor/symfony/config/Loader/FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'name' at position 17 in class App\\Controller\\ModuleController. at /var/www/html/PHP-Framework/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2018-06-19 10:28:23] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::urlRedirectAction","_route":"modulemodule_index","path":"/module/","permanent":true,"scheme":null,"httpPort":80,"httpsPort":443},"request_uri":"http://192.168.33.10/index.php/module","method":"GET"} []
[2018-06-19 10:28:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 10:28:23] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/index.php/module/","method":"GET"} []
[2018-06-19 10:28:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 10:28:23] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 10:28:23] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist" at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2018-06-19 10:28:24] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"b54cf0","_route":"_wdt"},"request_uri":"http://192.168.33.10/index.php/_wdt/b54cf0","method":"GET"} []
[2018-06-19 11:46:36] php.DEBUG: Warning: unlink(/var/www/html/PHP-Framework/symfony/var/cache/de_/ContainerY1rmveu.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":871,\"trace\":[{\"file\":\"/var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Kernel.php\",\"line\":665,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-06-19 12:03:13] request.INFO: Matched route "home_page". {"route":"home_page","route_parameters":{"_controller":"App\\Controller\\AppController::index","_route":"home_page"},"request_uri":"http://192.168.33.10/","method":"GET"} []
[2018-06-19 12:03:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:03:13] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/" is not callable. Expected method "index" on class "App\Controller\AppController", did you mean "indexAction"?" at /var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 91 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/\" is not callable. Expected method \"index\" on class \"App\\Controller\\AppController\", did you mean \"indexAction\"? at /var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Controller/ControllerResolver.php:91)"} []
[2018-06-19 12:03:16] request.INFO: Matched route "home_page". {"route":"home_page","route_parameters":{"_controller":"App\\Controller\\AppController::index","_route":"home_page"},"request_uri":"http://192.168.33.10/","method":"GET"} []
[2018-06-19 12:03:16] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:03:16] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/" is not callable. Expected method "index" on class "App\Controller\AppController", did you mean "indexAction"?" at /var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 91 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/\" is not callable. Expected method \"index\" on class \"App\\Controller\\AppController\", did you mean \"indexAction\"? at /var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Controller/ControllerResolver.php:91)"} []
[2018-06-19 12:03:26] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/index.php/module/","method":"GET"} []
[2018-06-19 12:03:26] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:03:27] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:03:27] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist" at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2018-06-19 12:03:27] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"cfb40f","_route":"_wdt"},"request_uri":"http://192.168.33.10/index.php/_wdt/cfb40f","method":"GET"} []
[2018-06-19 12:09:49] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-06-19 12:10:06] console.ERROR: Error thrown while running command "'doctine:migrations:migrate'". Message: "There are no commands defined in the "doctine:migrations" namespace.  Did you mean one of these?     doctrine     doctrine:cache     doctrine:database     doctrine:generate     doctrine:mapping     doctrine:migrations     doctrine:query     doctrine:schema" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"doctine:migrations\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:generate\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema at /var/www/html/PHP-Framework/symfony/vendor/symfony/console/Application.php:564)","command":"'doctine:migrations:migrate'","message":"There are no commands defined in the \"doctine:migrations\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:generate\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema"} []
[2018-06-19 12:14:33] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:14:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:14:33] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:14:33] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist" at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2018-06-19 12:14:34] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"d14f67","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/d14f67","method":"GET"} []
[2018-06-19 12:15:06] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-06-19 12:15:20] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-06-19 12:15:20] doctrine.DEBUG: CREATE TABLE migration_versions (version VARCHAR(255) NOT NULL, PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2018-06-19 12:15:20] doctrine.DEBUG: SELECT version FROM migration_versions [] []
[2018-06-19 12:15:20] doctrine.DEBUG: SELECT version FROM migration_versions WHERE version IN ('20180619093639', '20180619120950', '20180619121506') ORDER BY version DESC LIMIT 1 [] []
[2018-06-19 12:15:20] doctrine.DEBUG: SELECT version FROM migration_versions [] []
[2018-06-19 12:15:32] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:15:32] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:15:33] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:15:33] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist" at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.module' doesn't exist at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2018-06-19 12:15:34] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"e78af3","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/e78af3","method":"GET"} []
[2018-06-19 12:16:39] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-06-19 12:16:40] doctrine.DEBUG: CREATE TABLE module (id_module INT AUTO_INCREMENT NOT NULL, libelle_module VARCHAR(50) NOT NULL, prix_module DOUBLE PRECISION NOT NULL, PRIMARY KEY(id_module)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB [] []
[2018-06-19 12:16:40] doctrine.DEBUG: INSERT INTO migration_versions (version) VALUES (?) ["20180619093639"] []
[2018-06-19 12:16:40] doctrine.DEBUG: "COMMIT" [] []
[2018-06-19 12:16:40] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-06-19 12:16:40] doctrine.DEBUG: CREATE TABLE module (id_module INT AUTO_INCREMENT NOT NULL, libelle_module VARCHAR(50) NOT NULL, prix_module DOUBLE PRECISION NOT NULL, PRIMARY KEY(id_module)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB [] []
[2018-06-19 12:16:40] doctrine.DEBUG: "ROLLBACK" [] []
[2018-06-19 12:16:40] console.ERROR: Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing 'CREATE TABLE module (id_module INT AUTO_INCREMENT NOT NULL, libelle_module VARCHAR(50) NOT NULL, prix_module DOUBLE PRECISION NOT NULL, PRIMARY KEY(id_module)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'module' already exists" {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableExistsException(code: 0): An exception occurred while executing 'CREATE TABLE module (id_module INT AUTO_INCREMENT NOT NULL, libelle_module VARCHAR(50) NOT NULL, prix_module DOUBLE PRECISION NOT NULL, PRIMARY KEY(id_module)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'module' already exists at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:49, Doctrine\\DBAL\\Driver\\PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'module' already exists at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'module' already exists at /var/www/html/PHP-Framework/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)","command":"doctrine:migrations:migrate","message":"An exception occurred while executing 'CREATE TABLE module (id_module INT AUTO_INCREMENT NOT NULL, libelle_module VARCHAR(50) NOT NULL, prix_module DOUBLE PRECISION NOT NULL, PRIMARY KEY(id_module)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'module' already exists"} []
[2018-06-19 12:16:40] console.DEBUG: Command "doctrine:migrations:migrate" exited with code "1" {"command":"doctrine:migrations:migrate","code":1} []
[2018-06-19 12:17:02] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:17:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:17:02] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:17:02] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "module_new" as such route does not exist.")." at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig line 36 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"module_new\" as such route does not exist.\"). at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig:36, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"module_new\" as such route does not exist. at /var/www/html/PHP-Framework/symfony/var/cache/dev/srcDevDebugProjectContainerUrlGenerator.php:48)"} []
[2018-06-19 12:17:03] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"7b6a0c","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/7b6a0c","method":"GET"} []
[2018-06-19 12:18:44] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:18:44] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:18:45] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:18:45] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"e6a59f","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/e6a59f","method":"GET"} []
[2018-06-19 12:19:07] request.INFO: Matched route "modulemodule_new". {"route":"modulemodule_new","route_parameters":{"_controller":"App\\Controller\\ModuleController::new","_route":"modulemodule_new"},"request_uri":"http://192.168.33.10/module/new","method":"GET"} []
[2018-06-19 12:19:07] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:19:07] translation.WARNING: Translation not found. {"id":"Libelle module","domain":"messages","locale":"en"} []
[2018-06-19 12:19:07] translation.WARNING: Translation not found. {"id":"Prix module","domain":"messages","locale":"en"} []
[2018-06-19 12:19:08] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"2dd211","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/2dd211","method":"GET"} []
[2018-06-19 12:19:22] request.INFO: Matched route "modulemodule_new". {"route":"modulemodule_new","route_parameters":{"_controller":"App\\Controller\\ModuleController::new","_route":"modulemodule_new"},"request_uri":"http://192.168.33.10/module/new","method":"POST"} []
[2018-06-19 12:19:22] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:19:24] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-06-19 12:19:24] doctrine.DEBUG: INSERT INTO module (libelle_module, prix_module) VALUES (?, ?) {"1":"chaise","2":5} []
[2018-06-19 12:19:24] doctrine.DEBUG: "COMMIT" [] []
[2018-06-19 12:19:25] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:19:25] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:19:25] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:19:25] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Neither the property "idModule" nor one of the methods "idModule()", "getidModule()"/"isidModule()"/"hasidModule()" or "__call()" exist and have public access in class "App\Entity\Module"." at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig line 20 {"exception":"[object] (Twig_Error_Runtime(code: 0): Neither the property \"idModule\" nor one of the methods \"idModule()\", \"getidModule()\"/\"isidModule()\"/\"hasidModule()\" or \"__call()\" exist and have public access in class \"App\\Entity\\Module\". at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig:20)"} []
[2018-06-19 12:19:25] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"771367","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/771367","method":"GET"} []
[2018-06-19 12:36:39] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:36:39] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:36:39] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:36:39] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Neither the property "idModule" nor one of the methods "idModule()", "getidModule()"/"isidModule()"/"hasidModule()" or "__call()" exist and have public access in class "App\Entity\Module"." at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig line 20 {"exception":"[object] (Twig_Error_Runtime(code: 0): Neither the property \"idModule\" nor one of the methods \"idModule()\", \"getidModule()\"/\"isidModule()\"/\"hasidModule()\" or \"__call()\" exist and have public access in class \"App\\Entity\\Module\". at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig:20)"} []
[2018-06-19 12:36:40] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"1ee9ab","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/1ee9ab","method":"GET"} []
[2018-06-19 12:36:48] request.INFO: Matched route "home_page". {"route":"home_page","route_parameters":{"_controller":"App\\Controller\\AppController::index","_route":"home_page"},"request_uri":"http://192.168.33.10/","method":"GET"} []
[2018-06-19 12:36:48] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:36:48] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/" is not callable. Expected method "index" on class "App\Controller\AppController", did you mean "indexAction"?" at /var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 91 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/\" is not callable. Expected method \"index\" on class \"App\\Controller\\AppController\", did you mean \"indexAction\"? at /var/www/html/PHP-Framework/symfony/vendor/symfony/http-kernel/Controller/ControllerResolver.php:91)"} []
[2018-06-19 12:36:49] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"5e7b0e","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/5e7b0e","method":"GET"} []
[2018-06-19 12:38:31] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/index.php/module/","method":"GET"} []
[2018-06-19 12:38:31] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:38:31] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:38:31] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Neither the property "idModule" nor one of the methods "idModule()", "getidModule()"/"isidModule()"/"hasidModule()" or "__call()" exist and have public access in class "App\Entity\Module"." at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig line 20 {"exception":"[object] (Twig_Error_Runtime(code: 0): Neither the property \"idModule\" nor one of the methods \"idModule()\", \"getidModule()\"/\"isidModule()\"/\"hasidModule()\" or \"__call()\" exist and have public access in class \"App\\Entity\\Module\". at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig:20)"} []
[2018-06-19 12:38:32] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"4b507c","_route":"_wdt"},"request_uri":"http://192.168.33.10/index.php/_wdt/4b507c","method":"GET"} []
[2018-06-19 12:38:45] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:38:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:38:46] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:38:46] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Neither the property "idModule" nor one of the methods "idModule()", "getidModule()"/"isidModule()"/"hasidModule()" or "__call()" exist and have public access in class "App\Entity\Module"." at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig line 20 {"exception":"[object] (Twig_Error_Runtime(code: 0): Neither the property \"idModule\" nor one of the methods \"idModule()\", \"getidModule()\"/\"isidModule()\"/\"hasidModule()\" or \"__call()\" exist and have public access in class \"App\\Entity\\Module\". at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig:20)"} []
[2018-06-19 12:38:46] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"056d4f","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/056d4f","method":"GET"} []
[2018-06-19 12:38:49] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::urlRedirectAction","_route":"modulemodule_index","path":"/module/","permanent":true,"scheme":null,"httpPort":80,"httpsPort":443},"request_uri":"http://192.168.33.10/module","method":"GET"} []
[2018-06-19 12:38:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:38:49] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:38:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:38:49] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:38:49] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Neither the property "idModule" nor one of the methods "idModule()", "getidModule()"/"isidModule()"/"hasidModule()" or "__call()" exist and have public access in class "App\Entity\Module"." at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig line 20 {"exception":"[object] (Twig_Error_Runtime(code: 0): Neither the property \"idModule\" nor one of the methods \"idModule()\", \"getidModule()\"/\"isidModule()\"/\"hasidModule()\" or \"__call()\" exist and have public access in class \"App\\Entity\\Module\". at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig:20)"} []
[2018-06-19 12:38:50] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"29ce5c","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/29ce5c","method":"GET"} []
[2018-06-19 12:40:29] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:40:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:40:29] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:40:29] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "module_show" as such route does not exist.")." at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig line 24 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"module_show\" as such route does not exist.\"). at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig:24, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"module_show\" as such route does not exist. at /var/www/html/PHP-Framework/symfony/var/cache/dev/srcDevDebugProjectContainerUrlGenerator.php:54)"} []
[2018-06-19 12:40:30] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"1cd92a","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/1cd92a","method":"GET"} []
[2018-06-19 12:41:13] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:41:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:41:13] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:41:13] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "module_show" as such route does not exist.")." at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig line 24 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"module_show\" as such route does not exist.\"). at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig:24, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"module_show\" as such route does not exist. at /var/www/html/PHP-Framework/symfony/var/cache/dev/srcDevDebugProjectContainerUrlGenerator.php:54)"} []
[2018-06-19 12:41:14] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"845227","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/845227","method":"GET"} []
[2018-06-19 12:42:14] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:42:14] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:42:15] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:42:15] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "module_edit" as such route does not exist.")." at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig line 25 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"module_edit\" as such route does not exist.\"). at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig:25, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"module_edit\" as such route does not exist. at /var/www/html/PHP-Framework/symfony/var/cache/dev/srcDevDebugProjectContainerUrlGenerator.php:55)"} []
[2018-06-19 12:42:15] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"96d83c","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/96d83c","method":"GET"} []
[2018-06-19 12:42:36] request.INFO: Matched route "modulemodule_show". {"route":"modulemodule_show","route_parameters":{"_controller":"App\\Controller\\ModuleController::show","idModule":"1","_route":"modulemodule_show"},"request_uri":"http://192.168.33.10/module/1","method":"GET"} []
[2018-06-19 12:42:36] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:42:36] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 WHERE t0.id_module = ? LIMIT 1 ["1"] []
[2018-06-19 12:42:36] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "module_edit" as such route does not exist.")." at /var/www/html/PHP-Framework/symfony/templates/module/show.html.twig line 27 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"module_edit\" as such route does not exist.\"). at /var/www/html/PHP-Framework/symfony/templates/module/show.html.twig:27, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"module_edit\" as such route does not exist. at /var/www/html/PHP-Framework/symfony/var/cache/dev/srcDevDebugProjectContainerUrlGenerator.php:55)"} []
[2018-06-19 12:42:37] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"e678a7","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/e678a7","method":"GET"} []
[2018-06-19 12:42:40] request.INFO: Matched route "modulemodule_show". {"route":"modulemodule_show","route_parameters":{"_controller":"App\\Controller\\ModuleController::show","idModule":"0","_route":"modulemodule_show"},"request_uri":"http://192.168.33.10/module/0","method":"GET"} []
[2018-06-19 12:42:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:42:41] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 WHERE t0.id_module = ? LIMIT 1 ["0"] []
[2018-06-19 12:42:41] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "App\Entity\Module object not found by the @ParamConverter annotation." at /var/www/html/PHP-Framework/symfony/vendor/sensio/framework-extra-bundle/Request/ParamConverter/DoctrineParamConverter.php line 87 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): App\\Entity\\Module object not found by the @ParamConverter annotation. at /var/www/html/PHP-Framework/symfony/vendor/sensio/framework-extra-bundle/Request/ParamConverter/DoctrineParamConverter.php:87)"} []
[2018-06-19 12:42:41] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"c35bf1","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/c35bf1","method":"GET"} []
[2018-06-19 12:43:37] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:43:37] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:43:37] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:43:37] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "module_edit" as such route does not exist.")." at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig line 25 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"module_edit\" as such route does not exist.\"). at /var/www/html/PHP-Framework/symfony/templates/module/index.html.twig:25, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"module_edit\" as such route does not exist. at /var/www/html/PHP-Framework/symfony/var/cache/dev/srcDevDebugProjectContainerUrlGenerator.php:55)"} []
[2018-06-19 12:43:38] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"a3ceeb","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/a3ceeb","method":"GET"} []
[2018-06-19 12:45:45] request.INFO: Matched route "modulemodule_index". {"route":"modulemodule_index","route_parameters":{"_controller":"App\\Controller\\ModuleController::index","_route":"modulemodule_index"},"request_uri":"http://192.168.33.10/module/","method":"GET"} []
[2018-06-19 12:45:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-06-19 12:45:45] doctrine.DEBUG: SELECT t0.id_module AS id_module_1, t0.libelle_module AS libelle_module_2, t0.prix_module AS prix_module_3 FROM module t0 [] []
[2018-06-19 12:45:46] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"67ac0f","_route":"_wdt"},"request_uri":"http://192.168.33.10/_wdt/67ac0f","method":"GET"} []
